//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adicional
    {
        public Adicional()
        {
            this.Orcamento = new HashSet<Orcamento>();
        }
    
        public int AdicionalId { get; set; }
        public string Nome { get; set; }
        public bool Ativo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Orcamento> Orcamento { get; set; }
    }
}
