//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int AgendaId { get; set; }
        public Nullable<int> EventoId { get; set; }
        public int TipoEventoId { get; set; }
        public int LocalId { get; set; }
        public System.DateTime Data { get; set; }
        public string Observacao { get; set; }
    
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual Local Local { get; set; }
    }
}
