//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardapioRefeicaoItem
    {
        public int CardapioId { get; set; }
        public int RefeicaoId { get; set; }
        public int ItemId { get; set; }
    
        public virtual Cardapio Cardapio { get; set; }
        public virtual Item Item { get; set; }
        public virtual Refeicao Refeicao { get; set; }
    }
}
