//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cidade
    {
        public Cidade()
        {
            this.Local = new HashSet<Local>();
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int CidadeId { get; set; }
        public string Nome { get; set; }
        public int EstadoId { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Local> Local { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
