//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Orcamento = new HashSet<Orcamento>();
        }
    
        public int ClienteId { get; set; }
        public int CidadeId { get; set; }
        public string Logradouro { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Cpf { get; set; }
        public string Celular { get; set; }
        public string Telefone { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual ICollection<Orcamento> Orcamento { get; set; }
    }
}
