//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public Local()
        {
            this.Evento = new HashSet<Evento>();
            this.Imagem = new HashSet<Imagem>();
            this.Orcamento = new HashSet<Orcamento>();
        }
    
        public int LocalId { get; set; }
        public int CidadeId { get; set; }
        public string Nome { get; set; }
        public decimal Tamanho { get; set; }
        public string Logradouro { get; set; }
        public int Numero { get; set; }
        public bool Ativo { get; set; }
        public int Capacidade { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual ICollection<Imagem> Imagem { get; set; }
        public virtual ICollection<Orcamento> Orcamento { get; set; }
    }
}
