//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinela.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contexto : DbContext
    {
        public Contexto()
            : base("name=Contexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adicional> Adicional { get; set; }
        public DbSet<Agenda> Agenda { get; set; }
        public DbSet<Cardapio> Cardapio { get; set; }
        public DbSet<CardapioRefeicaoItem> CardapioRefeicaoItem { get; set; }
        public DbSet<Cidade> Cidade { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Evento> Evento { get; set; }
        public DbSet<Imagem> Imagem { get; set; }
        public DbSet<Item> Item { get; set; }
        public DbSet<Local> Local { get; set; }
        public DbSet<Pessoa> Pessoa { get; set; }
        public DbSet<Refeicao> Refeicao { get; set; }
        public DbSet<TipoEvento> TipoEvento { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
