//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEvento
    {
        public TipoEvento()
        {
            this.Orcamento = new HashSet<Orcamento>();
            this.Evento = new HashSet<Evento>();
        }
    
        public int TipoEventoId { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Orcamento> Orcamento { get; set; }
        public virtual ICollection<Evento> Evento { get; set; }
    }
}
